os: linux
dist: trusty
language: cpp
env:
- CXX_COMPILER=g++-7       BUILD_TYPE=Debug
- CXX_COMPILER=g++-7       BUILD_TYPE=Release
- CXX_COMPILER=clang++-5.0 BUILD_TYPE=Debug    
- CXX_COMPILER=clang++-5.0 BUILD_TYPE=Release   
- CXX_COMPILER=clang++-6.0 BUILD_TYPE=Debug    
- CXX_COMPILER=clang++-6.0 BUILD_TYPE=Release   

before_install:
- |
  sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
  sudo add-apt-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main"
  sudo add-apt-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main"

- |
  sudo apt-get update -qq
    
install:

################################################################################
# Install the latest gcc and clang compilers plus code coverage generator
# Boost.Test needs to be built with gcc-7, but Ubuntu 14.04 provides 4.8
# ./bootstrap.sh needs to find gcc-7 and ./b2 needs to find g++-7
# gcc-7 needs binutils-2.26 for LTO builds, but Ubuntu 14.04 provides 2.24
################################################################################
- |
  sudo apt-get install g++-7 binutils-2.26 lcov
  sudo apt-get install clang-5.0 lldb-5.0 lld-5.0
  sudo apt-get install clang-6.0 lldb-6.0 lld-6.0

- |
  sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90
  sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  export PATH=/usr/lib/binutils-2.26/bin:${PATH}
  
################################################################################
# All manual dependencies are installed in ${TRAVIS_BUILD_DIR}/../deps
################################################################################
- |
  DEPS_DIR="${TRAVIS_BUILD_DIR}/../deps"
  mkdir -p ${DEPS_DIR}
  
################################################################################
# Install the latest Boost and build Boost.Test (compiled with g++-7)
################################################################################
- |
  cd ${DEPS_DIR}
  BOOST_URL="https://dl.bintray.com/boostorg/release/1.64.0/source/boost_1_64_0.tar.bz2"
  mkdir boost-1.64.0 && travis_retry wget --quiet -O - ${BOOST_URL} | tar --strip-components=1 -xj -C boost-1.64.0
  cd boost-1.64.0 && ./bootstrap.sh --with-libraries=test && sudo ./b2 -d0 install

################################################################################
# Install the latest CMake
################################################################################
- |
  cd ${DEPS_DIR}
  CMAKE_URL="http://www.cmake.org/files/v3.9/cmake-3.9.0-Linux-x86_64.tar.gz"
  mkdir cmake-3.9.0 && travis_retry wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake-3.9.0
  export PATH=${DEPS_DIR}/cmake-3.9.0/bin:${PATH}

################################################################################
# Install the dependent GitHub repositories xstd and hash_append
################################################################################
- |
  cd ${DEPS_DIR}/..
  git clone https://github.com/rhalbersma/xstd.git
  mkdir -p ext && cd ext
  git clone https://github.com/rhalbersma/hash_append.git
  cd ..

before_script:
- |
  cd ${TRAVIS_BUILD_DIR}
  mkdir build && cd build
  cmake .. -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
 
script: 
- |
  make -j2
  ctest -E "search|traversal"
  travis_wait ctest -R "traversal" -E "board08x08"
  if [ ${BUILD_TYPE} == "Release" ]; then travis_wait ctest -R "board08x08"; fi

after_success:
- |
  lcov --capture --directory .. --output-file coverage.info
  bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
